#!/usr/bin/env sh
a=$(mktemp --suffix=.html)

if [ $1 ]; then
  cp $1 $a
else
  cat > $a < /dev/stdin
fi

# echo $a >> /tmp/log

(~/.local/node_modules/.bin/electron ~/.neomutt/html-viewer/main.js $a && rm $a) &
