#!/usr/bin/env sh
maildir=$1
account=$2
box=$3

if [ -z "$account" ]
then
    account=*
fi

if [ -z "$box" ]
then
    box="INBOX"
fi

new=$(ls $maildir/$account/$box/new | wc -l)
if [ $new != '0' ]; then
   notify-send "$account/$box: $new unread message(s)"
fi
